{% set name = "starkbank-ecdsa" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24422395e8682ac22a5b20ba3d7418d62e1a927aef29e8ddb5e678662be6b643

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ellipticcurve
    - ellipticcurve.utils

about:
  home: https://github.com/starkbank/ecdsa-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A lightweight and fast pure python ECDSA library

extra:
  recipe-maintainers:
    - cjmartian
