{% set name = "starkbank-ecdsa" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71dec991bf6f5bf80cb0a57141ca69aae87e12a0385105feca87e26e7efa3681

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ellipticcurve
    - ellipticcurve.utils

about:
  home: https://github.com/starkbank/ecdsa-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A lightweight and fast pure python ECDSA library

extra:
  recipe-maintainers:
    - cjmartian
